<?php

/**
 * @file
 * Primary module hooks for Drupal Bot module.
 */

use Drupal\Core\Render\Element;
use Drupal\drupal_bot\Entity\DrupalBotMessage;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function drupal_bot_theme() {
  return [
    'drupal_bot_message' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for drupal bot templates.
 *
 * Default template: drupal-bot-message.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the drupal bot information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_drupal_bot_message(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function drupal_bot_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish drupal bots.
      $storage = \Drupal::entityTypeManager()->getStorage('drupal_bot_message');
      $drupal_bot_message_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($drupal_bot_message_ids) as $drupal_bot_message) {
        $drupal_bot_message->set('status', FALSE);
        $drupal_bot_message->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize drupal bots.
      $storage = \Drupal::entityTypeManager()->getStorage('drupal_bot_message');
      $drupal_bot_message_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($drupal_bot_message_ids) as $drupal_bot_message) {
        $drupal_bot_message->setOwnerId(0);
        $drupal_bot_message->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function drupal_bot_user_predelete(UserInterface $account) {
  // Delete drupal bots.
  $storage = \Drupal::entityTypeManager()->getStorage('drupal_bot_message');
  $drupal_bot_message_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $drupal_bot_messages = $storage->loadMultiple($drupal_bot_message_ids);
  $storage->delete($drupal_bot_messages);
}
